#!/usr/bin/env python3
"""Generate BestPick daily activity report from git log + file inventory."""
import os, subprocess, datetime, pathlib

REPO_ROOT = pathlib.Path(__file__).parent.parent.parent
REPORT_DIR = REPO_ROOT / 'reports'
REPORT_DIR.mkdir(exist_ok=True)

now_vn = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=7)))
date_str = now_vn.strftime('%Y-%m-%d')
time_str = now_vn.strftime('%H:%M')
session = '08-morning' if now_vn.hour < 12 else '20-evening'
fname = REPORT_DIR / f'{date_str}-{session}.md'

def sh(cmd):
    return subprocess.check_output(cmd, shell=True, text=True, cwd=REPO_ROOT).strip()

since = (now_vn - datetime.timedelta(hours=12)).strftime('%Y-%m-%dT%H:%M:%S')
try:
    commits = sh(f'git log --since="{since}" --pretty=format:"%h|%an|%s|%ar" -n 30')
    commit_lines = [c for c in commits.split('\n') if c.strip()]
except Exception as e:
    commit_lines = [f'(git log failed: {e})']

try:
    files = sh(f'git log --since="{since}" --name-only --pretty=format: | sort -u | grep -v "^$" | head -20')
    file_lines = [f for f in files.split('\n') if f.strip()]
except Exception:
    file_lines = []

try:
    total_files = sh('git ls-files | wc -l')
    repo_size = sh('du -sh --exclude=.git . 2>/dev/null | cut -f1') or '?'
    latest_commit = sh('git log -1 --pretty=format:"%ar - %s"')
except Exception:
    total_files = repo_size = latest_commit = '?'

try:
    idx_size = (REPO_ROOT / 'index.html').stat().st_size if (REPO_ROOT / 'index.html').exists() else 0
    idx_size_kb = f'{idx_size/1024:.1f} KB'
except Exception:
    idx_size_kb = '?'

report = f"""# BestPick - Daily Report

**Time:** {date_str} {time_str} (Vietnam GMT+7) - session **{session}**

---

## Activity (last 12 hours)

- **Commits:** {len(commit_lines)}
- **Files touched:** {len(file_lines)}

### Recent commits
"""
if commit_lines:
    for line in commit_lines[:10]:
        parts = line.split('|')
        if len(parts) == 4:
            h, author, msg, when = parts
            report += f"- `{h}` - {when} - **{msg}** - {author}\n"
else:
    report += "- _No commits in the last 12h._\n"

report += "\n### Files changed\n"
if file_lines:
    for f in file_lines[:15]:
        report += f"- `{f}`\n"
else:
    report += "- _No file changes._\n"

report += f"""
---

## Repo snapshot

- **Total files:** {total_files}
- **Repo size:** {repo_size}
- **Latest commit:** {latest_commit}
- **index.html (mockup):** {idx_size_kb}

---

## Quick links

- **Live mockup VI:** https://snape1987.github.io/bestpick-mockupvn/
- **Repo:** https://github.com/snape1987/bestpick-mockupvn
- **Actions tab:** https://github.com/snape1987/bestpick-mockupvn/actions

---

_Auto-generated by GitHub Actions every 8 AM and 8 PM Vietnam time. Runs on GitHub cloud - does not require your computer to be on._
"""

fname.write_text(report, encoding='utf-8')
print(f'Wrote {fname}')

readme = REPORT_DIR / 'README.md'
existing = readme.read_text(encoding='utf-8') if readme.exists() else '# Daily Reports\n\nAuto-generated 2x/day. Newest at top.\n\n'
new_entry = f'- [{date_str} {session}](./{fname.name})\n'
if new_entry not in existing:
    lines = existing.split('\n')
    insert_at = 4 if len(lines) > 4 else len(lines)
    lines.insert(insert_at, new_entry.rstrip())
    readme.write_text('\n'.join(lines), encoding='utf-8')